const mongoose = require("mongoose");
const { Profile, User } = require("../modules/user/model");
require("dotenv").config();

const uri = process.env.MONGODB_URI || "mongodb://localhost:27016/matchill";

const users = [
  ["Hùng Nguyễn", "hungnv@gmail.com"],
  ["tranthilan", "lantt@gmail.com"],
  ["Tùng Lê Boyy", "tunglv@gmail.com"],
  ["PHAM Thi Hoa", "hoapt@gmail.com"],
  ["sơnhoàng", "sonhv@gmail.com"],
  ["Đặng Yến Nhi", "yendt@gmail.com"],
  ["phuc.vo", "phucvv@gmail.com"],
  ["Hạnh Bùi", "hanhbt@gmail.com"],
  ["ducphan99", "ducpv@gmail.com"],
  ["Đỗ Thị Nhung", "nhungdt@gmail.com"],
  ["TUYETNGUYEN", "tuyetnt@gmail.com"],
  ["Thắng Trần", "thangtv@gmail.com"],
  ["lexuan_", "xuanlt@gmail.com"],
  ["Long Phạm Đẹp Trai", "longpv@gmail.com"],
  ["hoangthihong", "honght@gmail.com"],
  ["Hải Đặng Văn", "haidv@gmail.com"],
  ["Mỹmỹ Võ", "myvt@gmail.com"],
  ["tienBUI", "tienbv@gmail.com"],
  ["Phan Vân", "vanpt@gmail.com"],
  ["dodung.vn", "dungdv@gmail.com"],
  ["Huệ Nguyễn", "huent@gmail.com"],
  ["hieptran", "hieptv@gmail.com"],
  ["Lý Lê Xinh", "lylt@gmail.com"],
  ["CUONG Pham Van", "cuongpv@gmail.com"],
  ["bíchhoàng", "bichht@gmail.com"],
  ["Trường Đặng", "truongdv@gmail.com"],
  ["kim.vo", "kimvt@gmail.com"],
  ["Phương Bùi", "phuongbv@gmail.com"],
  ["hienphan99", "hienpt@gmail.com"],
  ["Đỗ Văn Thịnh", "thinhdv@gmail.com"],
  ["daonguyen", "daont@gmail.com"],
  ["Lợi Trần", "loitv@gmail.com"],
  ["PHUONG Le Thi", "phuonglt@gmail.com"],
  ["nghĩaphạm", "nghiapv@gmail.com"],
  ["Hương Hoàng Xinh", "huonght@gmail.com"],
  ["canh.dang", "canhdv@gmail.com"],
  ["Hằng Võ", "hangvt@gmail.com"],
  ["HuyBui99", "huybv@gmail.com"],
  ["Phan Thị Hải", "haipt@gmail.com"],
  ["hoadovan", "hoadv@gmail.com"],
  ["Sang Nguyễn", "sangnv@gmail.com"],
  ["lienTRAN", "lientt@gmail.com"],
  ["Hoàng Lê Văn", "hoanglv@gmail.com"],
  ["nguyetpham_", "nguyetpt@gmail.com"],
  ["Toản Hoàng", "toanhv@gmail.com"],
  ["THUY Dang Thi", "thuydt@gmail.com"],
  ["khangvo99", "khangvv@gmail.com"],
  ["Tâm Bùi", "tambt2@gmail.com"],
  ["dongphan.vn", "dongpv@gmail.com"],
  ["Nga Đỗ", "ngadt@gmail.com"],
  ["THUNGUYEN", "thunt@gmail.com"],
  ["Bình Trần Zai", "binhtv@gmail.com"],
  ["lephuc", "phuclt@gmail.com"],
  ["Thái Phạm", "thaipv@gmail.com"],
  ["ngọchoàng", "ngoht@gmail.com"],
  ["Tú Đặng", "tudv@gmail.com"],
  ["VO Thi Sau", "sauvt@gmail.com"],
  ["haubui.99", "haubv@gmail.com"],
  ["Thanh Phan", "thanhpt@gmail.com"],
  ["phuocdo", "phuocdv@gmail.com"],
  ["Cúc Nguyễn Thị", "cucnt@gmail.com"],
  ["VuTran", "vutv@gmail.com"],
  ["hồnglê", "honglt@gmail.com"],
  ["Lộc Phạm", "locpv@gmail.com"],
  ["OANH Hoang Thi", "oanhht@gmail.com"],
  ["khanhdang_", "khanhdv@gmail.com"],
  ["Trà Võ", "travt@gmail.com"],
  ["taibui99", "taibv@gmail.com"],
  ["Thơm Phan Thị", "thompt@gmail.com"],
  ["Bảy Đỗ", "baydv@gmail.com"],
  ["TUYET.NGUYEN", "tuyetnt2@gmail.com"],
  ["trungTRAN", "trungtv@gmail.com"],
  ["Thắm Lê", "thamlt@gmail.com"],
  ["Hiếu Phạm Zai", "hieupv@gmail.com"],
  ["nụhoàng", "nuht@gmail.com"],
  ["Lâm Đặng", "lamdv@gmail.com"],
  ["HA VO", "havt@gmail.com"],
  ["dobui.vn", "dobv@gmail.com"],
  ["Lan Phan", "lanpt@gmail.com"],
  ["tandodv", "tandv@gmail.com"],
  ["Toàn Nguyễn", "toannv@gmail.com"],
  ["laitran", "laitt@gmail.com"],
  ["Tâm Lê", "tamlv@gmail.com"],
  ["NHAN Pham Thi", "nhanpt@gmail.com"],
  ["khoahoang99", "khoahv@gmail.com"],
  ["Diễm Đặng", "diemdt@gmail.com"],
  ["Hội Võ Văn", "hoivv@gmail.com"],
  ["thoabui_", "thoabt@gmail.com"],
  ["Bách Phan", "bachpv@gmail.com"],
  ["DUNG Do Thi", "dungdt@gmail.com"],
  ["hồngnguyễn", "hongnt@gmail.com"],
  ["Triều Trần", "trieutv@gmail.com"],
  ["Ánh Lê Xinh", "anhlt@gmail.com"],
  ["tupham.vn", "tupv@gmail.com"],
  ["Loan Hoàng Thị", "loanht@gmail.com"],
  ["tungdang99", "tungdv@gmail.com"],
  ["Cẩm Võ", "camvt@gmail.com"],
  ["NhanBui", "nhanbv@gmail.com"],
  ["thúyphan", "thuypt@gmail.com"],
  ["Huân Đỗ Văn", "huandv@gmail.com"],
  ["Hạ Nguyễn", "hant@gmail.com"],
  ["duytran_", "duytv@gmail.com"],
  ["TINH Le Thi", "tinhtl@gmail.com"],
  ["Lực Phạm", "lucpv@gmail.com"],
  ["sươnghoàng", "suonght@gmail.com"],
  ["Tuyển Đặng Văn", "tuyendv@gmail.com"],
  ["Ái Võ", "aivt@gmail.com"],
  ["hungbui99", "hungbv@gmail.com"],
  ["Xoan Phan Thị", "xoanpt@gmail.com"],
  ["chiendo.vn", "chiendv@gmail.com"],
  ["DUYEN Nguyen Thi", "duyennt@gmail.com"],
  ["Khải Trần", "khaitv@gmail.com"],
  ["hồilê", "hoilt@gmail.com"],
  ["Thọ Phạm", "thopv@gmail.com"],
  ["LUAN Hoang Thi", "luanht@gmail.com"],
  ["hiendang_", "hiendv@gmail.com"],
  ["Như Võ", "nhuvt@gmail.com"],
  ["dungBUI99", "dungbv@gmail.com"],
  ["Tươi Phan", "tuoipt@gmail.com"],
  ["chinhdo.vn", "chinhdv@gmail.com"],
  ["Bền Nguyễn", "bennv@gmail.com"],
  ["Trúc Trần Thị", "tructt@gmail.com"],
  ["hoanle99", "hoanlv@gmail.com"],
  ["BINH Pham Thi", "binhpt@gmail.com"],
  ["Phú Hoàng Zai", "phuhv@gmail.com"],
  ["Dân Đặng", "dandt@gmail.com"],
  ["nhatvo_", "nhatvv@gmail.com"],
  ["Quyên Bùi", "quyenbt@gmail.com"],
  ["Thuận Phan Văn", "thuanpv@gmail.com"],
  ["TUYEN Do Thi", "tuyendt@gmail.com"],
  ["giangnguyen99", "giangnt@gmail.com"],
  ["Thông Trần", "thongtv@gmail.com"],
  ["minhlê", "minhlt@gmail.com"],
  ["doanpham.vn", "doanpv@gmail.com"],
  ["Nhiên Hoàng Thị", "nhienht@gmail.com"],
  ["Hợp Đặng Văn", "hopdv@gmail.com"],
  ["TUYET VO", "tuyetvt@gmail.com"],
  ["thubui_", "thubv@gmail.com"],
  ["Cúc Phan", "cucpt@gmail.com"],
  ["Thành Đỗ Văn", "thanhdv@gmail.com"],
  ["Lệ Nguyễn", "lent@gmail.com"],
  ["manhtran99", "manhtv@gmail.com"],
  ["CAM Le Thi", "camlt@gmail.com"],
  ["Quân Phạm", "quanpv@gmail.com"],
  ["hậuhoàng", "hauht@gmail.com"],
  ["biendang.vn", "biendv@gmail.com"],
  ["Sa Võ Thị", "savt@gmail.com"],
  ["Thủy Bùi Zai", "thuybv@gmail.com"],
  ["HUONG Phan Thi", "huongpt@gmail.com"],
  ["luongdo_", "luongdv@gmail.com"],
  ["Kiều Nguyễn", "kieunt@gmail.com"],
  ["TinTran", "tintv@gmail.com"],
  ["mỹlê", "mylt@gmail.com"],
  ["sypham.vn", "sypv@gmail.com"],
  ["Ngà Hoàng Thị", "ngaht@gmail.com"],
  ["Quảng Đặng", "quangdv@gmail.com"],
  ["NHI VO", "nhivt@gmail.com"],
  ["anbui99", "anbv@gmail.com"],
  ["Ly Phan", "lypt@gmail.com"],
  ["Tạo Đỗ Văn", "taodv@gmail.com"],
  ["CHIN Nguyen Thi", "chinnt@gmail.com"],
  ["baytran_", "baytv@gmail.com"],
  ["Nguyên Lê", "nguyenlt@gmail.com"],
  ["Tiệp Phạm Zai", "tieppv@gmail.com"],
  ["bônghoàng", "bonght@gmail.com"],
  ["phatdang.vn", "phatdv@gmail.com"],
  ["TRINH Vo Thi", "trinhvt@gmail.com"],
  ["Thanh Bùi", "thanhbv@gmail.com"],
  ["Nở Phan", "nopt@gmail.com"],
  ["buudo99", "buudv@gmail.com"],
  ["Tâm Nguyễn Thị", "tamnt@gmail.com"],
  ["NhanTran", "nhantv@gmail.com"],
  ["phụnglê", "phunglt@gmail.com"],
  ["diephpam.vn", "dieppv@gmail.com"],
  ["CUC Hoang Thi", "cucht@gmail.com"],
  ["Phước Đặng Văn", "phuocdv2@gmail.com"],
  ["Đào Võ", "daovt@gmail.com"],
  ["huynhbui_", "huynhbv@gmail.com"],
  ["Hòa Phan", "hoapt2@gmail.com"],
  ["Phú Đỗ", "phudv@gmail.com"],
  ["LY Nguyen Thi", "lynt@gmail.com"],
  ["nientran99", "nientv@gmail.com"],
  ["Nhung Lê", "nhunglt@gmail.com"],
  ["Siêu Phạm Văn", "sieupv@gmail.com"],
  ["hạnhhoàng", "hanhht@gmail.com"],
  ["thodang.vn", "thodv@gmail.com"],
  ["NHAN VO", "nhanvt@gmail.com"],
  ["Đức Bùi Zai", "ducbv@gmail.com"],
  ["Vui Phan", "vuipt@gmail.com"],
  ["toando_", "toandv@gmail.com"],
  ["Hảo Nguyễn Thị", "haont@gmail.com"],
  ["Hỷ Trần", "hytv@gmail.com"],
  ["ngàlê", "ngalt@gmail.com"],
  ["minhpham99", "minhpv@gmail.com"],
  ["THUAN Hoang Thi", "thuanht@gmail.com"],
  ["Trọng Đặng", "trongdv@gmail.com"],
  ["GAI VO", "gaivt@gmail.com"],
  ["tuyenbui.vn", "tuyenbv@gmail.com"],
  ["Liễu Phan Thị", "lieupt@gmail.com"],
  ["Oai Đỗ Văn", "oaidv@gmail.com"],
  ["Nga Nguyễn", "ngant2@gmail.com"],
  ["binhtran_", "binhtv2@gmail.com"],
  ["Tuyết Lê", "tuyetlt@gmail.com"],
  ["Chất Phạm Zai", "chatpv@gmail.com"],
  ["NHAM Hoang Thi", "nhamht@gmail.com"],
  ["xuyendang99", "xuyendv@gmail.com"],
  ["huyềnvõ", "huyenvt@gmail.com"],
  ["Nghệ Bùi", "nghebv@gmail.com"],
  ["Ngọt Phan", "ngotpt@gmail.com"],
  ["ninhdo.vn", "ninhdv@gmail.com"],
  ["TRA Nguyen Thi", "trant@gmail.com"],
  ["Quế Trần", "quetv@gmail.com"],
];

async function run() {
  try {
    await mongoose.connect(uri);
    console.log("-> Kết nối database thành công.");
    let updateCount = 0;

    for (const [newName, email] of users) {
      // Tìm user theo email
      const user = await User.findOne({ email: email.toLowerCase() });
      if (user) {
        // Cập nhật trường name ở Profile collection bằng user_id tìm được
        const result = await Profile.updateOne(
          { user_id: user._id },
          { $set: { name: newName } },
        );
        if (result.modifiedCount > 0) {
          updateCount++;
        }
      }
    }
    console.log(
      `-> Đã đổi tên thành công cho ${updateCount}/${users.length} tài khoản.`,
    );
  } catch (err) {
    console.error("-> Lỗi trong quá trình update:", err);
  } finally {
    await mongoose.disconnect();
    console.log("-> Đã ngắt kết nối database.");
  }
}

run();


